In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# check pytorch version
torch.__version__

'1.12.0'

### Intro to tensors in pytorch

In [64]:
# Tensors are a way to represent data in a computer memory.
# Tensors are a multi-dimensional array of numbers.
# Tensors can be of any size and shape.
# Tensors can be of any type.

#### create a scalar tensor

In [ ]:
scalar = torch.tensor(10)
scalar

In [5]:
# Attributes of a scalar tensor
scalar.item() # returns the scalar value
scalar.dtype # returns the data type of the tensor

10

In [15]:
vector = torch.tensor([1,2,3]) # create a vector tensor
vector.shape

In [17]:
matrix = torch.tensor([[1,2,3],[4,5,6]]) # create a matrix tensor
matrix.shape

torch.Size([2, 3])

In [23]:
matrix[0] # returns the values at the first row

tensor([1, 2, 3])

In [25]:
tensor = torch.tensor([[[1,2,4],[5,6,7],[8,9,0], [11,12,13]]]) # create a tensor with 3 dimensions
tensor

tensor([[[ 1,  2,  4],
         [ 5,  6,  7],
         [ 8,  9,  0],
         [11, 12, 13]]])

In [26]:
tensor.shape

torch.Size([1, 4, 3])

In [31]:
tensor[0,:, 1]

tensor([ 2,  6,  9, 12])

In [32]:
# Creating random Tensors
# The torch.rand function returns a tensor of random numbers drawn from a uniform distribution.
# The torch.randn function returns a tensor of random numbers drawn from a normal distribution.
# The torch.empty function returns a tensor of zeros.
# The torch.zeros function returns a tensor of zeros.
# The torch.ones function returns a tensor of ones.
# The torch.randint function returns a tensor of random integers.
# The torch.randperm function returns a tensor of random permutations.

rand_dist = torch.rand((3,3))

tensor([[0.7306, 0.2444, 0.2748],
        [0.7789, 0.4969, 0.8186],
        [0.4327, 0.9859, 0.8825]])

In [35]:
## Tensor of random numbers drawn from a normal distribution
randn = torch.randn((3,3))
randn

tensor([[ 0.7090,  0.7798, -1.1736],
        [-0.7551,  0.4027, -2.4941],
        [ 1.1577, -0.1630, -0.2470]])

In [36]:
rand_emp = torch.empty((3,3))
rand_emp

tensor([[0.0000e+00, 2.5244e-29, 0.0000e+00],
        [2.5244e-29, 1.1210e-44, 6.7262e-44],
        [7.8473e-44, 6.3058e-44, 6.7262e-44]])

In [37]:
## Tensor of zeros
rand_zeros = torch.zeros((3,3))
rand_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [45]:
## Tensor of Ones
rand_ones = torch.ones([3,3])
rand_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
rand_int = torch.randint(0,10,(3,3))
rand_int

tensor([[4, 1, 7],
        [8, 1, 0],
        [8, 5, 1]])

In [49]:
rand_perm = torch.randperm(10)
rand_perm

tensor([3, 7, 0, 8, 2, 1, 5, 4, 6, 9])

In [54]:
image = torch.rand(size=(224,224,3))
image

tensor([[[0.5883, 0.4222, 0.0186],
         [0.8455, 0.9189, 0.5782],
         [0.6354, 0.5553, 0.4284],
         ...,
         [0.2730, 0.8541, 0.7923],
         [0.2383, 0.4597, 0.1693],
         [0.0504, 0.5306, 0.4999]],

        [[0.5147, 0.5788, 0.2183],
         [0.8599, 0.6117, 0.1179],
         [0.0217, 0.1642, 0.2628],
         ...,
         [0.7509, 0.2006, 0.1829],
         [0.3915, 0.7870, 0.8076],
         [0.3366, 0.3295, 0.8507]],

        [[0.9504, 0.2005, 0.6565],
         [0.0521, 0.1483, 0.4264],
         [0.0719, 0.8581, 0.0965],
         ...,
         [0.1484, 0.1604, 0.0078],
         [0.1011, 0.8727, 0.2270],
         [0.7983, 0.8556, 0.0756]],

        ...,

        [[0.2969, 0.8252, 0.3920],
         [0.9259, 0.4606, 0.7545],
         [0.5435, 0.4900, 0.3169],
         ...,
         [0.0111, 0.3385, 0.3640],
         [0.6291, 0.7965, 0.0570],
         [0.7495, 0.7258, 0.4121]],

        [[0.5367, 0.2488, 0.5260],
         [0.9197, 0.9209, 0.0426],
         [0.

#### Create a range of tensors in pytorch

In [59]:
rang = torch.range(0,10, step=2)
rang

/var/folders/zf/nmlxjncx1y1dzrhzmb_8dm700000gn/T/ipykernel_51684/2106638349.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  rang = torch.range(0,10, step=2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [63]:
rang = torch.arange(0,2000, step=80)
rang

tensor([   0,   80,  160,  240,  320,  400,  480,  560,  640,  720,  800,  880,
         960, 1040, 1120, 1200, 1280, 1360, 1440, 1520, 1600, 1680, 1760, 1840,
        1920])

#### Tensor datatypes

You can create tensors of different numerical datatypes such as float16, float32, float64 and int16, int32, int64

In [65]:
tensor_float16 = torch.tensor([1,3,5], dtype=torch.float16)
tensor_float16

tensor([1., 3., 5.], dtype=torch.float16)

In [66]:
tensor_float32 = torch.tensor([1,3,5], dtype=torch.float32)
tensor_float32

tensor([1., 3., 5.])

In [67]:
tensor_float64 = torch.tensor([1,3,5], dtype=torch.float64)
tensor_float64

tensor([1., 3., 5.], dtype=torch.float64)

#### Tensor attributes (information about tensors)

In [74]:
print('Ndim: ', tensor.ndim) # returns the dimensions of a tensor
print('Shape: ', tensor.shape) #returns the shape of a tensor
print('Dtype: ', tensor.dtype) #returns the data type of a tensor
print('index: ', tensor[0]) # returns the item(s) in the 0th index of a tensor
print('index: ', tensor[0,0]) # returns the item(s) in the 0th and 1st index of a tensor
print('Device: ', tensor.device) # returns the device of a tensor

Ndim:  3
Shape:  torch.Size([1, 4, 3])
Dtype:  torch.int64
index:  tensor([[ 1,  2,  4],
        [ 5,  6,  7],
        [ 8,  9,  0],
        [11, 12, 13]])
index:  tensor([1, 2, 4])
Device:  cpu


#### Manipulating tensors

##### Some Tensor Operations
_Pytorch provides builtin functions to compute the some mathematical operations on all elements in a tensor._
- The torch.add function adds two tensors.
- The torch.sub function subtracts two tensors.
- The torch.mul function multiplies two tensors.
- The torch.div function divides two tensors.
- The torch.pow function raises a tensor to the power of another tensor.
- The torch.sqrt function returns the square root of a tensor.
- The torch.exp function returns the exponential of a tensor.
- The torch.log function returns the natural logarithm of a tensor.

In [79]:
tensor + 5 # adds 5 to each element of a tensor

tensor([[[ 6,  7,  9],
         [10, 11, 12],
         [13, 14,  5],
         [16, 17, 18]]])

In [80]:
tensor * 5 # multiplies 5 to each element of a tensor

tensor([[[ 5, 10, 20],
         [25, 30, 35],
         [40, 45,  0],
         [55, 60, 65]]])

In [81]:
tensor / 5 # divides 5 to each element of a tensor

tensor([[[0.2000, 0.4000, 0.8000],
         [1.0000, 1.2000, 1.4000],
         [1.6000, 1.8000, 0.0000],
         [2.2000, 2.4000, 2.6000]]])

In [82]:
tensor - 5 # subtracts 5 from each element of a tensor

tensor([[[-4, -3, -1],
         [ 0,  1,  2],
         [ 3,  4, -5],
         [ 6,  7,  8]]])

In [86]:
### let's start with an element wise multplication

tensor * tensor

tensor([[[  1,   4,  16],
         [ 25,  36,  49],
         [ 64,  81,   0],
         [121, 144, 169]]])

In [91]:
torch.matmul(tensor.squeeze(), tensor.squeeze().T)

tensor([[ 21,  45,  26,  87],
        [ 45, 110,  94, 218],
        [ 26,  94, 145, 196],
        [ 87, 218, 196, 434]])

In [93]:
%%time 
tensor * tensor

CPU times: user 45 µs, sys: 12 µs, total: 57 µs
Wall time: 65.1 µs


tensor([[[  1,   4,  16],
         [ 25,  36,  49],
         [ 64,  81,   0],
         [121, 144, 169]]])

In [95]:
%%time
torch.matmul(tensor.squeeze(), tensor.squeeze().T)


CPU times: user 606 µs, sys: 228 µs, total: 834 µs
Wall time: 2.7 ms


tensor([[ 21,  45,  26,  87],
        [ 45, 110,  94, 218],
        [ 26,  94, 145, 196],
        [ 87, 218, 196, 434]])