In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# check pytorch version
torch.__version__

'1.12.0'

In [3]:
# intro to tensors in pytorch
# Tensors are a way to represent data in a computer memory.
# Tensors are a multi-dimensional array of numbers.
# Tensors can be of any size and shape.
# Tensors can be of any type.

# create a scalar tensor
scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
# Attributes of a scalar tensor
scalar.item() # returns the scalar value
scalar.dtype # returns the data type of the tensor

10

In [15]:
vector = torch.tensor([1,2,3]) # create a vector tensor
vector.shape

In [17]:
matrix = torch.tensor([[1,2,3],[4,5,6]]) # create a matrix tensor
matrix.shape

torch.Size([2, 3])

In [23]:
matrix[0] # returns the values at the first row

tensor([1, 2, 3])

In [25]:
tensor = torch.tensor([[[1,2,4],[5,6,7],[8,9,0], [11,12,13]]]) # create a tensor with 3 dimensions
tensor

tensor([[[ 1,  2,  4],
         [ 5,  6,  7],
         [ 8,  9,  0],
         [11, 12, 13]]])

In [26]:
tensor.shape

torch.Size([1, 4, 3])

In [31]:
tensor[0,:, 1]

tensor([ 2,  6,  9, 12])

In [32]:
# Creating random Tensors
# The torch.rand function returns a tensor of random numbers drawn from a uniform distribution.
# The torch.randn function returns a tensor of random numbers drawn from a normal distribution.
# The torch.empty function returns a tensor of zeros.
# The torch.zeros function returns a tensor of zeros.
# The torch.ones function returns a tensor of ones.
# The torch.randint function returns a tensor of random integers.
# The torch.randperm function returns a tensor of random permutations.

rand_dist = torch.rand((3,3))

tensor([[0.7306, 0.2444, 0.2748],
        [0.7789, 0.4969, 0.8186],
        [0.4327, 0.9859, 0.8825]])

In [35]:
randn = torch.randn((3,3))
randn

tensor([[ 0.7090,  0.7798, -1.1736],
        [-0.7551,  0.4027, -2.4941],
        [ 1.1577, -0.1630, -0.2470]])

In [36]:
rand_emp = torch.empty((3,3))
rand_emp

tensor([[0.0000e+00, 2.5244e-29, 0.0000e+00],
        [2.5244e-29, 1.1210e-44, 6.7262e-44],
        [7.8473e-44, 6.3058e-44, 6.7262e-44]])

In [37]:
rand_zeros = torch.zeros((3,3))
rand_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [45]:
rand_ones = torch.ones([3,3])
rand_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [48]:
rand_int = torch.randint(0,10,(3,3))
rand_int

tensor([[4, 1, 7],
        [8, 1, 0],
        [8, 5, 1]])

In [49]:
rand_perm = torch.randperm(10)
rand_perm

tensor([3, 7, 0, 8, 2, 1, 5, 4, 6, 9])