In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# check pytorch version
torch.__version__

'1.12.0'

### Intro to tensors in pytorch

Tensors are a way to represent data in a computer memory.
<br>Tensors are a multi-dimensional array of numbers.
<br>Tensors can be of any size and shape.
<br>Tensors can be of any type.

#### create a scalar tensor

In [3]:
scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
# Attributes of a scalar tensor
scalar.item() # returns the scalar value

10

In [6]:
scalar.dtype # returns the data type of the tensor

torch.int64

In [8]:
vector = torch.tensor([1,2,3]) # create a vector tensor
vector.shape, vector

(torch.Size([3]), tensor([1, 2, 3]))

In [9]:
matrix = torch.tensor([[1,2,3],[4,5,6]]) # create a matrix tensor
matrix.shape, matrix

(torch.Size([2, 3]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

In [23]:
matrix[0] # returns the values at the first row

tensor([1, 2, 3])

In [13]:
tensor = torch.tensor([[[1,2,4],[5,6,7],[8,9,0], [11,12,13]]]) # create a tensor with 3 dimensions
tensor

tensor([[[ 1,  2,  4],
         [ 5,  6,  7],
         [ 8,  9,  0],
         [11, 12, 13]]])

In [14]:
tensor.shape

torch.Size([1, 4, 3])

In [15]:
tensor[0,:, 1]

tensor([ 2,  6,  9, 12])

# Creating random Tensors
* The torch.rand function returns a tensor of random numbers drawn from a uniform distribution.
* The torch.randn function returns a tensor of random numbers drawn from a normal distribution.
* The torch.empty function returns a tensor of zeros.
* The torch.zeros function returns a tensor of zeros.
* The torch.ones function returns a tensor of ones.
*  The torch.randint function returns a tensor of random integers.
* The torch.randperm function returns a tensor of random permutations.

In [16]:
rand_dist = torch.rand((3,3))
rand_dist

tensor([[0.4310, 0.6983, 0.7197],
        [0.8606, 0.0679, 0.1456],
        [0.0810, 0.0143, 0.5878]])

In [17]:
## Tensor of random numbers drawn from a normal distribution
randn = torch.randn((3,3))
randn

tensor([[ 0.0603, -0.5528, -0.0928],
        [-0.3252, -0.8327,  1.1438],
        [ 1.1094,  0.9643, -0.8869]])

In [21]:
rand_emp = torch.empty((3,3))
rand_emp

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
## Tensor of zeros
rand_zeros = torch.zeros((3,3))
rand_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
## Tensor of Ones
rand_ones = torch.ones([3,3])
rand_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [24]:
rand_int = torch.randint(0,10,(3,3))
rand_int

tensor([[5, 3, 5],
        [7, 8, 2],
        [8, 5, 4]])

In [25]:
rand_perm = torch.randperm(10)
rand_perm

tensor([1, 7, 4, 0, 6, 9, 8, 3, 2, 5])

In [26]:
image = torch.rand(size=(224,224,3))
image

tensor([[[0.7938, 0.2095, 0.7951],
         [0.3333, 0.8421, 0.2528],
         [0.5694, 0.1518, 0.0717],
         ...,
         [0.0435, 0.4787, 0.5140],
         [0.2706, 0.2989, 0.4046],
         [0.7540, 0.6064, 0.0679]],

        [[0.4938, 0.8626, 0.2224],
         [0.2732, 0.5218, 0.6903],
         [0.1239, 0.4968, 0.5044],
         ...,
         [0.5928, 0.6475, 0.1609],
         [0.3232, 0.2901, 0.2354],
         [0.5643, 0.1077, 0.1416]],

        [[0.5200, 0.9126, 0.0500],
         [0.5508, 0.6352, 0.5293],
         [0.4138, 0.0468, 0.6507],
         ...,
         [0.3750, 0.8788, 0.9921],
         [0.5587, 0.1156, 0.8047],
         [0.7328, 0.7993, 0.1037]],

        ...,

        [[0.9529, 0.9307, 0.6593],
         [0.6145, 0.6631, 0.3646],
         [0.1841, 0.9575, 0.0337],
         ...,
         [0.6841, 0.0775, 0.9207],
         [0.0102, 0.4311, 0.3039],
         [0.8643, 0.7772, 0.7812]],

        [[0.9945, 0.4465, 0.8230],
         [0.7884, 0.4790, 0.3312],
         [0.

### Create a range of tensors in pytorch

In [27]:
rang = torch.range(0,10, step=2)
rang

/var/folders/zf/nmlxjncx1y1dzrhzmb_8dm700000gn/T/ipykernel_27927/4046705229.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  rang = torch.range(0,10, step=2)


tensor([ 0.,  2.,  4.,  6.,  8., 10.])

In [63]:
rang = torch.arange(0,2000, step=80)
rang

tensor([   0,   80,  160,  240,  320,  400,  480,  560,  640,  720,  800,  880,
         960, 1040, 1120, 1200, 1280, 1360, 1440, 1520, 1600, 1680, 1760, 1840,
        1920])

### Tensor datatypes

You can create tensors of different numerical datatypes such as float16, float32, float64 and int16, int32, int64

In [28]:
tensor_float16 = torch.tensor([1,3,5], dtype=torch.float16)
tensor_float16

tensor([1., 3., 5.], dtype=torch.float16)

In [29]:
tensor_float32 = torch.tensor([1,3,5], dtype=torch.float32)
tensor_float32

tensor([1., 3., 5.])

In [30]:
tensor_float64 = torch.tensor([1,3,5], dtype=torch.float64)
tensor_float64

tensor([1., 3., 5.], dtype=torch.float64)

### Tensor attributes (information about tensors)

In [31]:
print('Ndim: ', tensor.ndim) # returns the dimensions of a tensor
print('Shape: ', tensor.shape) #returns the shape of a tensor
print('Dtype: ', tensor.dtype) #returns the data type of a tensor
print('index: ', tensor[0]) # returns the item(s) in the 0th index of a tensor
print('index: ', tensor[0,0]) # returns the item(s) in the 0th and 1st index of a tensor
print('Device: ', tensor.device) # returns the device of a tensor

Ndim:  3
Shape:  torch.Size([1, 4, 3])
Dtype:  torch.int64
index:  tensor([[ 1,  2,  4],
        [ 5,  6,  7],
        [ 8,  9,  0],
        [11, 12, 13]])
index:  tensor([1, 2, 4])
Device:  cpu


### Manipulating tensors (Tensor Operations)

_Pytorch provides builtin functions to compute the some mathematical operations on all elements in a tensor._
- The torch.add function adds two tensors.
- The torch.sub function subtracts two tensors.
- The torch.mul function multiplies two tensors.
- The torch.div function divides two tensors.
- The torch.pow function raises a tensor to the power of another tensor.
- The torch.sqrt function returns the square root of a tensor.
- The torch.exp function returns the exponential of a tensor.
- The torch.log function returns the natural logarithm of a tensor.

In [32]:
tensor + 5 # adds 5 to each element of a tensor

tensor([[[ 6,  7,  9],
         [10, 11, 12],
         [13, 14,  5],
         [16, 17, 18]]])

In [33]:
tensor * 5 # multiplies 5 to each element of a tensor

tensor([[[ 5, 10, 20],
         [25, 30, 35],
         [40, 45,  0],
         [55, 60, 65]]])

In [34]:
tensor / 5 # divides 5 to each element of a tensor

tensor([[[0.2000, 0.4000, 0.8000],
         [1.0000, 1.2000, 1.4000],
         [1.6000, 1.8000, 0.0000],
         [2.2000, 2.4000, 2.6000]]])

In [35]:
tensor - 5 # subtracts 5 from each element of a tensor

tensor([[[-4, -3, -1],
         [ 0,  1,  2],
         [ 3,  4, -5],
         [ 6,  7,  8]]])

In [36]:
### let's start with an element wise multplication

tensor * tensor

tensor([[[  1,   4,  16],
         [ 25,  36,  49],
         [ 64,  81,   0],
         [121, 144, 169]]])

In [37]:
torch.matmul(tensor.squeeze(), tensor.squeeze().T)

tensor([[ 21,  45,  26,  87],
        [ 45, 110,  94, 218],
        [ 26,  94, 145, 196],
        [ 87, 218, 196, 434]])

In [38]:
%%time 
tensor * tensor

CPU times: user 41 µs, sys: 6 µs, total: 47 µs
Wall time: 52 µs


tensor([[[  1,   4,  16],
         [ 25,  36,  49],
         [ 64,  81,   0],
         [121, 144, 169]]])

In [39]:
%%time
torch.matmul(tensor.squeeze(), tensor.squeeze().T)

CPU times: user 551 µs, sys: 522 µs, total: 1.07 ms
Wall time: 620 µs


tensor([[ 21,  45,  26,  87],
        [ 45, 110,  94, 218],
        [ 26,  94, 145, 196],
        [ 87, 218, 196, 434]])

### Finding the min, max, mean and sum

In [40]:
tensor.min(), tensor.max()

(tensor(0), tensor(13))

In [41]:
tensor.mean(dtype=torch.float32), tensor.sum(dtype=torch.float32)

(tensor(6.5000), tensor(78.))

In [42]:
tensor.squeeze().argmin(), tensor.squeeze().argmax()

(tensor(8), tensor(11))

In [43]:
tensor.squeeze().flatten()[8], tensor.squeeze().flatten()[11]

(tensor(0), tensor(13))

### Reshaping, viewing and stacking

In [44]:
new_tensor = torch.randint(0,100, (4,3))
new_tensor

tensor([[81, 78, 48],
        [46, 76, 90],
        [96, 45, 85],
        [61, 18, 77]])

In [147]:
# reshape new_tensor
new_tensor.permute(1,0)

tensor([[59, 13, 10, 55],
        [33, 32, 64, 91],
        [69, 87, 29, 84]])

In [152]:
x = torch.randn(2, 8, 5)
x.size()
torch.permute(x, (1, 2, 0)).size()

torch.Size([8, 5, 2])

### Squeezing, unsqueezing and permuting

In [156]:
tensor.squeeze() # removes the singleton dimensions

tensor([[ 1,  2,  4],
        [ 5,  6,  7],
        [ 8,  9,  0],
        [11, 12, 13]])

In [162]:
tensor.unsqueeze(0) # adds a singleton dimension

tensor([[[[ 1,  2,  4],
          [ 5,  6,  7],
          [ 8,  9,  0],
          [11, 12, 13]]]])

In [166]:
tensor.permute(1,2,0).shape # transpose the tensor

torch.Size([4, 3, 1])

### Pseudo Randomness in PyTorch

In [170]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

### Check if we are using a GPU with PyTorch
One key feature of pytorch is allows you decide if an operation is going to be run on the GPU or the CPU.
e.g.

```python
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

tensor = torch.rand(1, device=device)

```
By doing this you can run the tensor on the GPU if it is available.
**Note:** If a tensor is of device type `cuda` you can not automatically transform it into a numpy array. First covert it to a numpy array using `tensor.cpu()` method

In [173]:
torch.cuda.is_available() # returns true if a GPU is available

False

In [188]:
tensor = torch.rand([224,1000,3], device=device)
tensor

tensor([[[0.1712, 0.1170, 0.3688],
         [0.5366, 0.3300, 0.6468],
         [0.7222, 0.3218, 0.4508],
         ...,
         [0.8235, 0.2978, 0.5761],
         [0.7499, 0.4098, 0.5182],
         [0.1959, 0.3049, 0.2355]],

        [[0.2073, 0.2045, 0.5881],
         [0.4014, 0.8144, 0.0928],
         [0.8582, 0.8379, 0.6921],
         ...,
         [0.6604, 0.5686, 0.5791],
         [0.0998, 0.6248, 0.5315],
         [0.9076, 0.0639, 0.2505]],

        [[0.2638, 0.9545, 0.0444],
         [0.9898, 0.5918, 0.0317],
         [0.5858, 0.7498, 0.9373],
         ...,
         [0.2334, 0.9667, 0.6171],
         [0.3338, 0.1558, 0.2181],
         [0.7379, 0.6242, 0.6336]],

        ...,

        [[0.6428, 0.0256, 0.8170],
         [0.0220, 0.9024, 0.1055],
         [0.3903, 0.6022, 0.8950],
         ...,
         [0.2216, 0.2562, 0.5886],
         [0.8634, 0.5491, 0.8421],
         [0.5761, 0.1636, 0.9478]],

        [[0.2733, 0.4266, 0.9744],
         [0.9458, 0.3327, 0.5397],
         [0.

In [184]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' # check if cuda is available
device

'cpu'

In [183]:
torch.cuda.device_count() # returns the number of CUDA devices available

0